#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config/{nginx/site-confs,www,log/nginx,keys,log/php} \
	/run \
	/var/lib/nginx/tmp/client_body \
	/var/tmp/nginx

# copy config files
[[ ! -f /config/nginx/nginx.conf ]] && \
	cp /defaults/nginx.conf /config/nginx/nginx.conf
[[ ! -f /config/nginx/site-confs/default ]] && \
	cp /defaults/default /config/nginx/site-confs/default
[[ $(find /config/www -type f | wc -l) -eq 0 ]] && \
	cp /defaults/index.html /config/www/index.html

# first time application handling
[[ ! -d /app/NNTmux/ ]] && [ "$BRANCH" == "stable" ] && \
    echo "cloning stable branch into /app/NNTmux/" && \
    git clone --depth 1 --branch 0.x https://github.com/NNTmux/newznab-tmux.git /app/NNTmux/ && \
[[ ! -d /app/NNTmux/ ]] && [ "$BRANCH" == "dev" ] && \
    echo "cloning dev branch into /app/NNTmux/" && \
    git clone --depth 1 --branch dev https://github.com/NNTmux/newznab-tmux.git /app/NNTmux/ && \
[[ ! -d /app/NNTmux/vendor/ ]] && \
    echo "installing composer packages" && \
    composer global require hirak/prestissimo && \
    cd /app/NNTmux/ && composer install

# existing application handling
echo "Auto update set to: $AUTOUPDATE" && \
[ "$AUTOUPDATE" == "true" ] && \
    cd /app/NNTmux/ && php artisan nntmux:all

# fix max_execution_time in php.ini
sed -i "s#max_execution_time = 30.*#max_execution_time = 120#g" /etc/php/7.2/php.ini
# fix memory_limit in php.ini
sed -i "s#memory_limit = 128M.*#memory_limit = $PHPMEM#g" /etc/php/7.2/php.ini
# fix timezone in php.ini
sed -i "s#;date.timezone =.*#date.timezone = $TZ#g" /etc/php/7.2/php.ini
# enable error logging in php.ini
sed -i "s#error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT.*#error_reporting = E_ALL#g" /etc/php/7.2/php.ini
# fix php log location
sed -i "s#;error_log = php_errors.log.*#error_log = /config/log/php/clierror.log#g" /etc/php/7.2/php.ini
# fix php-fpm log location
sed -i "s#error_log = /var/log/php/7.2/php-fpm.log.*#error_log = /config/log/php/error.log#g" /etc/php/7.2/php-fpm.conf
# fix php-fpm listener
sed -i "s#listen = /run/php/php-fpm7.2.sock.*#listen = 127.0.0.1:9000#g" /etc/php/7.2/php-fpm.d/www.conf
# fix php-fpm user
sed -i "s#user = www-data.*#user = abc#g" /etc/php/7.2/php-fpm.d/www.conf
sed -i "s#group = www-data.*#group = abc#g" /etc/php/7.2/php-fpm.d/www.conf


# permissions
chown -R abc:abc \
	/app \
	/config \
	/run \
	/var/lib/nginx \
	/var/tmp/nginx
chmod -R g+w \
	/config/{nginx,www}
chmod -R 644 /etc/logrotate.d